services:
  postgres:
    image: postgres:15
    container_name: backend-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kadracoon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kadracoon-net

  web:
    build: .
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - .env
    command: bash /app/migrations.sh
    ports:
      - "8011:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
    networks:
      - kadracoon-net

  alembic:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - kadracoon-net

volumes:
  pgdata:

networks:
  kadracoon-net:
    external: true
